services:
  backend:
    build: ./backend
    container_name: devtrack-backend
    ports:
      - "3001:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/devtrack
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: devtrack-mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

