global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "devtrack-backend"
    static_configs:
      - targets: ["backend:3000"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["172.17.0.1:9100"]



